theme = "nightfox"

[editor]
color-modes = true
true-color = true
bufferline = "always"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-encoding"]
right = ["diagnostics", "selections", "position", "position-percentage"]
[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
