[[language]]
name = "java"
roots = ["pom.xml", "build.gradle"]
language-server = { command = "jdtls" }

[[language]]
name = "elixir"
auto-format = true
config = { dialyzerEnabled = true, fetchDeps = true, suggestSpecs = true , signatureAfterComplete = true }
