theme = "nightfox"

[editor]
color-modes = true
true-color = true
cursorline = true
bufferline = "always"
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-encoding"]
right = ["version-control", "diagnostics", "selections", "position", "position-percentage"]

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.normal]
"X" = "extend_line_above"
