[[language]]
name = "elixir"
auto-format = true
language-servers = ["elixir-ls"]

[[language]]
name = "go"
auto-format = true
formatter.command = "goimports"

[[language]]
name = "nix"
auto-format = true
formatter.command = "alejandra"

[[language]]
name = "python"
language-servers = ["pyright", "ruff"] # ruff, pylyzer, pyright
auto-format = true

[[language]]
name = "toml"
auto-format = true
formatter.command = "taplo"
formatter.args = ["fmt", "-"]

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"

[language-server.elixir-ls.config]
dialyzerEnabled = true
fetchDeps = true
suggestSpecs = true
signatureAfterComplete = true

[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onSave", outputPath = "$root/target/$dir/$name" }

# https://github.com/tekumara/typos-lsp/blob/main/docs/helix-config.md
[language-server.typos]
command = "typos-lsp"
config.diagnosticSeverity = "Warning"
