[[language]]
name = "elixir"
auto-format = true
language-servers = [ "elixir-ls" ]

[language-server.elixir-ls.config]
dialyzerEnabled = true
fetchDeps = true
suggestSpecs = true
signatureAfterComplete = true

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
