[general]
import = ["./themes/catppuccin-mocha.toml"]

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
# default: 11.25
size = 11.25

[font.normal]
family = "FiraCode Nerd Font Mono"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "None"
# dynamic_padding = true
dynamic_title = false
# opacity = 0.5
resize_increments = true
startup_mode = "Maximized"
title = ""
