# Links:
# https://github.com/catppuccin/helix
# https://github.com/helix-editor/helix/blob/master/runtime/themes/catppuccin_mocha.toml
# Struct members should be "text", not "blue", but there are no queries specific to them.
# https://github.com/catppuccin/helix/issues/56

inherits = "catppuccin_mocha"

# SYNTAX HIGHLIGHTING OVERRIDES
# These keys match tree-sitter scopes.

"namespace" = { fg = "text", modifiers = ["italic"] } # original is "yellow"
"type.parameter" = "peach"                            # original is "yellow", inherited from type
"variable.other.member" = "text"                      # original is "blue"
"operator" = "overlay2"                               # original "sky"
"label" = "mauve"                                     # original "sapphire", used for lifetimes
"constructor" = "teal"                                # original "sapphire"
"special" = "blue"                                    # fuzzy highlight, derives, ?, original "blue"
"function.macro" = "sapphire"                         # original "mauve"
